name: Test Documentation
on:
  # push will run on every pushed commit to any branch
  # EXCEPT to master and main, which the `publish.yml` handles
  push:
    branches-ignore:
      - master
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v6
      - uses: actions/checkout@v6
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - name: Add CNAME file
        run: echo 'docs.gen3.org' > ./docs/CNAME
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: pip install zensical
      - run: zensical build --clean
